// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3hO3Fk7esrm-mI8PgM_3IHjqHf8MI92M',
    appId: '1:396265164729:web:014645f51ebe783e7a3068',
    messagingSenderId: '396265164729',
    projectId: 'appex-f4b57',
    authDomain: 'appex-f4b57.firebaseapp.com',
    storageBucket: 'appex-f4b57.firebasestorage.app',
    measurementId: 'G-X2Y48FZBPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-xc3IRaP7x8WUWQntPIStbiR199MOpnQ',
    appId: '1:396265164729:android:9c5644f38ab3ec627a3068',
    messagingSenderId: '396265164729',
    projectId: 'appex-f4b57',
    storageBucket: 'appex-f4b57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF0-otBOzxRi4lVJYOkIB5ivaGwJVszJU',
    appId: '1:396265164729:ios:8afecc3d2c262fd97a3068',
    messagingSenderId: '396265164729',
    projectId: 'appex-f4b57',
    storageBucket: 'appex-f4b57.firebasestorage.app',
    iosBundleId: 'com.example.appex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF0-otBOzxRi4lVJYOkIB5ivaGwJVszJU',
    appId: '1:396265164729:ios:8afecc3d2c262fd97a3068',
    messagingSenderId: '396265164729',
    projectId: 'appex-f4b57',
    storageBucket: 'appex-f4b57.firebasestorage.app',
    iosBundleId: 'com.example.appex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3hO3Fk7esrm-mI8PgM_3IHjqHf8MI92M',
    appId: '1:396265164729:web:328af584196d789b7a3068',
    messagingSenderId: '396265164729',
    projectId: 'appex-f4b57',
    authDomain: 'appex-f4b57.firebaseapp.com',
    storageBucket: 'appex-f4b57.firebasestorage.app',
    measurementId: 'G-WLDEVPPMCX',
  );
}
